import { execSync } from "child_process";
import { existsSync } from "fs";
import { mkdir, rm, writeFile } from "fs/promises";
import path from "path";

import tiged from "tiged";

import { writeGeneratedFiles } from "./generators/files";
import type { ProjectConfig } from "./prompts";
import { getTemplate } from "./templates";
import { logger } from "./utils/logger";
import { replaceInDir } from "./utils/replace";

const TEMPLATE_REPO = process.env.QUADSTACK_TEMPLATE_REPO ?? "HarbdhulQuadri/quadstack";

export async function scaffold(
  projectDir: string,
  config: ProjectConfig,
): Promise<void> {
  // ─── Clone base template ──────────────────────────────────────────────────
  logger.step("Cloning template...");

  if (existsSync(projectDir)) {
    logger.error(`Directory "${path.basename(projectDir)}" already exists.`);
    process.exit(1);
  }

  await mkdir(projectDir, { recursive: true });

  try {
    const emitter = tiged(TEMPLATE_REPO, { cache: false, force: true, verbose: false });
    await emitter.clone(projectDir);
  } catch (err) {
    logger.error(`Failed to clone template from "${TEMPLATE_REPO}".`);
    logger.error(err instanceof Error ? err.message : String(err));
    await rm(projectDir, { recursive: true, force: true });
    process.exit(1);
  }

  // Remove the CLI tool from the cloned project
  await rm(path.join(projectDir, "create-quadstack"), { recursive: true, force: true });

  logger.success("Template cloned");

  // ─── Remove unused apps ───────────────────────────────────────────────────
  for (const app of ["web", "admin"]) {
    if (!config.apps.includes(app)) {
      await rm(path.join(projectDir, "apps", app), { recursive: true, force: true });
      logger.info(`Removed apps/${app}`);
    }
  }

  // ─── Rename package scope ─────────────────────────────────────────────────
  logger.step(`Setting package scope to @${config.packageScope}...`);

  await replaceInDir(projectDir, [
    { from: "quadstack",   to: config.packageScope },
    { from: "@quadstack/", to: `@${config.packageScope}/` },
  ]);

  logger.success("Scope renamed");

  // ─── Apply app-type template ──────────────────────────────────────────────
  const template = getTemplate(config.appType);

  if (template.id !== "blank") {
    logger.step(`Applying ${template.name} template...`);

    const files = template.generate(config.packageScope, config);
    await writeGeneratedFiles(projectDir, files);

    logger.success(`${template.name} schema, validators and routers generated`);
    logger.info("All generated files are regular TypeScript — edit them freely.");
  }

  // ─── Generate .env ────────────────────────────────────────────────────────
  logger.step("Generating .env...");
  await generateEnv(projectDir, config);
  logger.success(".env created");

  // ─── Platform deploy config ───────────────────────────────────────────────
  if (config.platform !== "none") {
    logger.step(`Generating ${config.platform} deploy config...`);
    await generateDeployConfig(projectDir, config);
    logger.success("Deploy config created");
  }

  // ─── Update README ────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectDir, "README.md"),
    generateReadme(config, template.name),
    "utf-8",
  );

  // ─── Git init ─────────────────────────────────────────────────────────────
  if (config.git) {
    logger.step("Initialising git...");
    try {
      execSync("git init", { cwd: projectDir, stdio: "ignore" });
      execSync("git add .", { cwd: projectDir, stdio: "ignore" });
      execSync(
        `git commit -m "chore: initial commit (${template.name} template via create-quadstack)"`,
        { cwd: projectDir, stdio: "ignore" },
      );
      logger.success("Git repository initialised");
    } catch {
      logger.warn("Git init failed — run `git init` manually.");
    }
  }

  // ─── Install dependencies ─────────────────────────────────────────────────
  if (config.installDeps) {
    logger.step("Installing dependencies...");
    execSync("pnpm install", { cwd: projectDir, stdio: "inherit" });
    logger.success("Dependencies installed");
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function generateEnv(dir: string, config: ProjectConfig) {
  const lines: string[] = [
    "# Generated by create-quadstack",
    `# App type: ${config.appType}`,
    "",
    "# ─── Database ───────────────────────────────────────────────",
    "DATABASE_URL=postgresql://user:password@host:5432/dbname",
    "",
    "# ─── Better Auth ─────────────────────────────────────────────",
    "# Generate with: openssl rand -base64 32",
    "BETTER_AUTH_SECRET=",
    "BETTER_AUTH_URL=http://localhost:3000",
    "",
    "# ─── App URLs ────────────────────────────────────────────────",
    "NEXT_PUBLIC_WEB_URL=http://localhost:3000",
  ];

  if (config.apps.includes("admin")) {
    lines.push("NEXT_PUBLIC_ADMIN_URL=http://localhost:3001");
  }

  lines.push(
    "",
    "# ─── Email (Resend) ─────────────────────────────────────────",
    "RESEND_API_KEY=re_",
    "EMAIL_FROM=noreply@yourdomain.com",
  );

  if (config.authProviders.includes("google")) {
    lines.push("", "# ─── Google OAuth ───────────────────────────────────────────", "GOOGLE_CLIENT_ID=", "GOOGLE_CLIENT_SECRET=");
  }
  if (config.authProviders.includes("facebook")) {
    lines.push("", "# ─── Facebook OAuth ─────────────────────────────────────────", "AUTH_FACEBOOK_ID=", "AUTH_FACEBOOK_SECRET=");
  }
  if (config.authProviders.includes("github")) {
    lines.push("", "# ─── GitHub OAuth ───────────────────────────────────────────", "AUTH_GITHUB_ID=", "AUTH_GITHUB_SECRET=");
  }

  if (config.payments.includes("stripe")) {
    lines.push("", "# ─── Stripe ─────────────────────────────────────────────────", "STRIPE_SECRET_KEY=sk_test_", "STRIPE_WEBHOOK_SECRET=whsec_", "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_");
  }
  if (config.payments.includes("paystack")) {
    lines.push("", "# ─── Paystack ───────────────────────────────────────────────", "PAYSTACK_SECRET_KEY=sk_test_", "NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=pk_test_");
  }
  if (config.payments.includes("paypal")) {
    lines.push("", "# ─── PayPal ─────────────────────────────────────────────────", "PAYPAL_CLIENT_ID=", "PAYPAL_CLIENT_SECRET=", "PAYPAL_WEBHOOK_ID=");
  }

  if (config.media) {
    lines.push(
      "",
      "# ─── Cloudinary ─────────────────────────────────────────────",
      "# Sign up free at https://cloudinary.com",
      "CLOUDINARY_CLOUD_NAME=",
      "CLOUDINARY_API_KEY=",
      "CLOUDINARY_API_SECRET=",
      "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=",
    );
  }

  lines.push(
    "",
    "# ─── Upstash Redis (rate limiting) ──────────────────────────",
    "# Optional — rate limiting falls back to no-op without these",
    "UPSTASH_REDIS_REST_URL=",
    "UPSTASH_REDIS_REST_TOKEN=",
  );

  await writeFile(path.join(dir, ".env"), lines.join("\n") + "\n", "utf-8");
}

async function generateDeployConfig(dir: string, config: ProjectConfig): Promise<void> {
  const apps = config.apps;

  if (config.platform === "vercel") {
    // One vercel.json per app
    for (const app of apps) {
      await writeFile(
        path.join(dir, "apps", app, "vercel.json"),
        JSON.stringify({
          framework: "nextjs",
          installCommand: "cd ../.. && pnpm install --frozen-lockfile",
          buildCommand:   `cd ../.. && pnpm build --filter=@${config.packageScope}/${app}...`,
          outputDirectory: ".next",
        }, null, 2) + "\n",
        "utf-8",
      );
    }

    // CD workflow
    const deployJobs = apps.map((app) => `
  deploy-${app}:
    name: Deploy ${app} → Vercel
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec vercel deploy --prod --token=\${{ secrets.VERCEL_TOKEN }} --cwd apps/${app}
        env:
          VERCEL_ORG_ID: \${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: \${{ secrets.VERCEL_${app.toUpperCase()}_PROJECT_ID }}`).join("\n");

    await writeFile(
      path.join(dir, ".github", "workflows", "deploy.yml"),
      `name: Deploy\n\non:\n  push:\n    branches: [main]\n\njobs:${deployJobs}\n`,
      "utf-8",
    );
  }

  if (config.platform === "railway") {
    await writeFile(
      path.join(dir, "railway.toml"),
      `[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm start:web"
restartPolicyType = "on_failure"
`,
      "utf-8",
    );
  }

  if (config.platform === "flyio") {
    for (const app of apps) {
      const port = app === "admin" ? 3001 : 3000;
      await writeFile(
        path.join(dir, "apps", app, "fly.toml"),
        `app = "${config.packageScope}-${app}"
primary_region = "iad"

[build]

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
`,
        "utf-8",
      );
    }
  }
}

function generateReadme(config: ProjectConfig, templateName: string): string {
  const appList = config.apps
    .map((a) => `- **${a}**: \`pnpm dev:${a}\``)
    .join("\n");

  return `# ${config.name}

${templateName} app scaffolded with [create-quadstack](https://github.com/quadstack-dev/quadstack).

## Setup

\`\`\`bash
pnpm install
# Fill in .env — it was pre-generated for your chosen providers
pnpm db:push        # creates all database tables
pnpm dev            # start all apps
\`\`\`

## Apps

${appList}

## Docs

- [Getting started](docs/getting-started.md)
- [Frontend guide](docs/contributing/frontend.md)
- [Backend guide](docs/contributing/backend.md)
- [Database guide](docs/contributing/database.md)
- [Architecture](docs/architecture.md)
`;
}
